# Generated by Django 3.0.3 on 2020-05-19 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='date_borrowed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
