# Generated by Django 3.0.3 on 2020-05-20 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_auto_20200519_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='date_return',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 19, 59, 5, 452225)),
        ),
    ]
