# Generated by Django 3.0.3 on 2020-04-25 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('surname', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=80)),
                ('post_code', models.CharField(default='', max_length=6)),
                ('phone_number', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=10)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('profile_picture', models.ImageField(default='static/library/images/news.jpg', upload_to='static/library/images/profile_pictures')),
                ('rules_agreement', models.BooleanField(default=False)),
                ('pesel', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
