# Generated by Django 3.0.3 on 2020-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(default='', max_length=300)),
                ('year', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('time', models.IntegerField(default=14)),
                ('is_available', models.BooleanField(default=True)),
                ('edition', models.IntegerField(default=1)),
            ],
        ),
    ]
