# Generated by Django 3.0.3 on 2020-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default_book_img.png', upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
